config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  resources :communities do
    resources :subscriptions
  end

  resources :submissions do
    resources :comments

    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end

    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", as: "comment_unsubscribe"

  devise_for :users
  root "submissions#index"

  resources :profiles, only: :show
end

app/models/comment.rb
class Comment < ApplicationRecord
  include VotesCountable
  belongs_to :submission
  belongs_to :user

  validates :reply, presence: true

  acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy, :show, :upvote, :downvote]
  before_action :set_submission

  def new

  end

  def create
    @comment = @submission.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        send_comment_notification
        format.turbo_stream
        format.html { redirect_to submission_path(@submission), notice: "Comment created successfully" }
      else
        format.turbo_stream
        format.html { redirect_to submission_path{@submission}, alert: "Comment could not be created" }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream
        format.html { redirect_to submission_path(@submission), notice: "Comment create successfully" }
      else
        format.turbo_stream
        format.html { redirect_to submission_path(@submission), alert: "Comment could not be created." }
      end
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to submission_path(@submission), notice: "Comment deleted successfully" }
    end
  end

  def upvote
    respond_to do |format|
      unless current_user.voted_for? @comment
        @comment.upvote_by current_user
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{dom_id(@comment)}_votes_count", @comment.total_vote_count)
      }
      else
        format.html { redirect_to submission_path(@submission), alert: "You already voted for this submission."}
      end
    end
  end

  def downvote
    respond_to do |format|
      unless current_user.voted_for? @comment
        @comment.downvote_by current_user
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{dom_id(@comment)}_votes_count", @comment.total_vote_count)
      }
      else
        format.html { redirect_to submission_path(@submission), alert: "You already voted for this submission."}
      end
    end
  end

  private

    def send_comment_notification
      unless @submission.user == @comment.user
        if @submission.user.comment_subscription?
          SubmissionMailer.with(comment: @comment, submission: @submission).new_response.deliver_later
        end
      end
    end

    def set_submission
      @submission = Submission.find(params[:submission_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:reply, :submission_id)
    end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <div class="border p-4 rounded my-4 flex items-start">
    <%= render "comments/voting", submission: @submission, comment: comment %>

    <div>
      <p class="font-semibold"><%= comment.user.username %></p>
      <div class="prose prose-indigo"><%= comment.reply %></div>
      <% if author_of?(comment) %>
        <div class="flex items-end space-x-3">
          <%= link_to "Edit comment", edit_submission_comment_path(comment.submission, comment), class: "text-indigo-600 underline" %>
          <%= button_to "Delete comment", submission_comment_path(comment.submission, comment), method: :delete, class: "text-indigo-600 underline" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<p class="text-sm text-gray-600 my-2">comment as <%= link_to current_user.username, profile_path(current_user), class: "text-indigo-600 underline" %>
</p>
<!-- Add autocomplete: "off" to text area -->
<%= form_with(model: [@submission, comment]) do |f| %>
  <%= f.text_area :reply, class: "input min-h-[100px] resize-none", placeholder: "What are your thoughts?", autocomplete: "off" %>
  <%= f.submit class: "btn btn-indigo text-base font-normal mt-6" %>
<% end %>

app/views/comments/_voting.html.erb
<div class="w-10 flex flex-col items-start">
  <% if user_signed_in? %>
    <%= button_to upvote_submission_comment_path(submission, comment), method: :put, class: "block text-center group" do %>
      <%= render_svg "icons/up-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
    <div class="flex justify-center pl-1">
      <span class="text-gray-700 text-center block" id="<%= dom_id(comment)%>_votes_count"><%= comment.total_vote_count %></span>
    </div>
    <%= button_to downvote_submission_comment_path(submission, comment), method: :put, class: "block text-center group"  do %>
      <%= render_svg "icons/down-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "block text-center group", data: { turbo: false } do %>
      <%= render_svg "icons/up-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
    <div class="flex justify-center pl-1">
      <span class="text-gray-700 text-center block" id="<%= dom_id(comment)%>_votes_count"><%= comment.total_vote_count %></span>
    </div>
    <%= link_to new_user_session_path, class: "block text-center group", data: { turbo: false }  do %>
      <%= render_svg "icons/down-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
  <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "#{dom_id(@submission)}_comments" do %>
  <%= render "comments/comment", comment: @comment %>
<% end %>
<!-- Update id to generic "new_comment_form" and use "update" stream action instead of replace -->
<%= turbo_stream.update "new_comment_form" do %>
  <%= render "comments/form", comment: Comment.new %>
<% end %>
<%= turbo_stream.replace "#{dom_id(@submission)}_comment_count" do %>
  <p id="<%= dom_id(@submission)%>_comment_count"><%= pluralize(@submission.comments.size, 'comment') %></p>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>
<!-- Update new comment form for good measure -->
<%= turbo_stream.update "new_comment_form" do %>
  <%= render "comments/form", comment: Comment.new %>
<% end %>
<!-- Update comment count -->
<%= turbo_stream.update "#{dom_id(@submission)}_comment_count" do %>
  <p id="<%= dom_id(@submission)%>_comment_count"><%= pluralize(@submission.comments.size, 'comment') %></p>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "comments/form", comment: @comment %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@comment) do %>
  <%= render "comments/comment", comment: @comment %>
<% end %>
<%= turbo_stream.replace "#{dom_id(@submission)}_comments_form" do %>
  <%= render "comments/form", comment: Comment.new %>
<% end %>