config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  resources :communities do
    resources :subscriptions
  end

  resources :submissions do
    resources :comments

    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end

    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", as: "comment_unsubscribe"

  devise_for :users
  root "submissions#index"

  resources :profiles, only: :show
end

app/models/submission.rb
class Submission < ApplicationRecord
  include VotesCountable
  belongs_to :user
  belongs_to :community
  has_one_attached :media
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { maximum: 8000 }
  validates :url, url: true, allow_blank: true
  validate :body_or_url
  validate :content_exists

  acts_as_votable

  private

    def body_or_url
      unless url.blank? || body.blank?
        # If both url and body are present (i.e., neither is blank),
        # the method proceeds to the next nested unless statement.
        # This statement uses the XOR (exclusive or) operator ^ to check
        # if exactly one of the url or body attributes is blank.
        # The condition unless url.blank? ^ body.blank? will be true
        # if both attributes are either present or absent.
        unless url.blank? ^ body.blank?
          errors.add(:base, "Specify a URL or a body, not both")
        end
      end
    end

    def content_exists
      if url.blank? && body.blank? && !media.attached?
        errors.add(:base, "Specify a URL, a body, or upload a media file")
      end
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_submission, only: %i[show edit update destroy upvote downvote]
  before_action :authenticate_user!, except: %i[index show unsubscribe]

  # GET /submissions or /submissions.json
  def index
    if user_signed_in?
      @feed_title = "My Feed"
      @submissions = current_user.subscribed_submissions
    else
      @feed_title = "Select a communnity"
      @submissions = Submission.all
    end
  end

  # GET /submissions/1 or /submissions/1.json
  def show
    @community = @submission.community
    @subscription = @community.subscriptions.where(user: current_user).first
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)
    @submission.user_id = current_user.id

    respond_to do |format|
      if @submission.save
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    respond_to do |format|
      if current_user.voted_for? @submission
        format.html { redirect_back fallback_location: root_path, alert: "You already voted for this submission." }
      else
        @submission.upvote_by current_user
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace("#{dom_id(@submission)}_votes_count", @submission.total_vote_count)
        }
      end
    end
  end

  def downvote
    respond_to do |format|
      if current_user.voted_for? @submission
        format.html { redirect_back fallback_location: root_path, alert: "You already voted for this submission." }
      else
        @submission.downvote_by current_user
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace("#{dom_id(@submission)}_votes_count", @submission.total_vote_count)
        }
      end
    end
  end

  def unsubscribe
    user = User.find_by_unsubscribe_hash(params[:unsubscribe_hash])
    user.update(comment_subscription: false)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = Submission.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def submission_params
    params.require(:submission).permit(:title, :body, :url, :media, :community_id)
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<div data-controller="tabs">
  <%= form_with(model: submission) do |form| %>
    <% if submission.errors.any? %>
      <div class="bg-red-50 text-red-700 p-4 rounded border border-red-300 mb-6">
        <h2 class="leading-tight font-bold mb-3"><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

        <ul>
          <% submission.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-6 w-full lg:w-2/5">
      <label for="#">Community</label>
      <div class="relative">
        <%= form.select :community_id, Community.all.collect { |u| [u.name, u.id] }, { prompt: "Choose a community" }, { class: "select"} %>
        <div class="pointer-events-none absolute inset-y-5 right-2 flex items-center">
          <%= render_svg "icons/chevron-down", styles: "fill-current w-4 h-4 text-gray-500" %>
        </div>
      </div>
    </div>

    <label for="submission_type">Submission type</label>
    <nav role="submission type" class="mb-6">
      <ul class="divide-y lg:divide-x grid grid-cols-1 lg:grid-cols-3 gap-0 border rounded shadow-sm">
        <li>
          <a href="#"
          data-action="click->tabs#toggle"
            data-tab-id="text"
            data-tabs-target="button"
            class="p-4 flex items center justify-center group hover:text-indigo-600">
            <%= render_svg "icons/text", styles: "group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
            Text
          </a>
        </li>
        <li>
          <a href="#"
          data-action="click->tabs#toggle"
            data-tab-id="url"
            data-tabs-target="button"
            class="p-4 flex items center justify-center group hover:text-indigo-600">
            <%= render_svg "icons/link", styles: "group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
            URL
          </a>
        </li>
        <li>
          <a href="#"
          data-action="click->tabs#toggle"
            data-tab-id="media"
            data-tabs-target="button"
            class="p-4 flex items center justify-center group hover:text-indigo-600">
            <%= render_svg "icons/image", styles: "group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
            Image or Video
          </a>
        </li>
      </ul>
    </nav>

    <div class="mb-6">
      <%= form.label :title %>
      <%= form.text_field :title, class: "input" %>
    </div>

    <div data-tabs-target="text" class="mb-6">
      <%= form.label :body %>
      <%= form.text_area :body, class: "input min-h-[200px]" %>
    </div>

    <div data-tabs-target="url" class="hidden mb-6">
      <%= form.label :url %>
      <%= form.text_field :url, class: "input" %>
    </div>

    <div data-tabs-target="media" class="hidden mb-6">
      <%= form.label :media do %>
        <span class="mb-1 inline-block">Attach a video or image</span>
        <%= form.file_field :media, class: "block w-full text-sm
        text-gray-600
          file:mr-4 file:py-2 file:px-4
          file:rounded-full file:border-0
          file:text-sm file:font-semibold
          file:bg-indigo-50 file:text-indigo-700
          hover:file:bg-indigo-100" %>
      <% end %>
    </div>

    <%= form.submit class: "btn btn-indigo" %>
  <% end %>
</div>

app/views/submissions/_guidelines.html.erb
<h3 class="font-bold text-xl mb-4">Posting to Webbit</h3>
<ol class="list-none leading-loose p-0 text-sm divide-y">
  <li class="py-1">Remember to be human</li>
  <li class="py1">Behave like you would be in real life</li>
  <li class="py-1">Look for the original source of content</li>
  <li class="py-1">Search for duplicates before posting</li>
  <li class="py-1">Read the community's news</li>
</ol>

app/views/submissions/_submission.html.erb
<li id="<%= dom_id submission %>">
  <div class="py-3 flex items-start flex-wrap">
    <%= render "submissions/voting", submission: submission %>
    <% if submission.media.attached? %>
      <div class="w-2/12">
        <%= link_to submission do %>
          <% if submission.media.video? %>
            <%= video_tag submission.media %>
          <% else %>
            <%= image_tag submission.media.variant(resize_to_fit: [200, 200]), alt: submission.title, class: "rounded" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class="flex-1 <%= "pl-4" if submission.media.attached? %>">
      <h3 class="mb-1 flex flex-wrap">
        <%= link_to submission.title, submission, class: "no-underline font-semibold items-center text-xl hover:text-indigo-600" %>
        <% if submission.url? %>
          <span class="pl-2 text-xs font-normal font-mono text-indigo-400 tracking-tigher">
            <%= truncate(submission.url, length: 18) %>
          </span>
        <% end %>
      </h3>
      <p class="font-mono text-sm text-gray-600 hover:text-indigo-600 mb-2 group">
        w/<%= link_to submission.community.name, community_path(submission.community), class: "group-hover:text-indigo-600" %>
      </p>
      <% if submission.body? %>
        <div class="text-sm text-gray-700">
          <%= truncate(submission.body, length: 140) %>
        </div>
      <% end %>
      <div class="flex flex-wrap items-center justify-between">
        <div class="mt-3 flex-1">
          <%= link_to submission_path(submission, anchor: "comment_section"), class: "flex items-center space-x-3 group-hover:text-indigo-600" do %>
            <%= render_svg "icons/conversation", styles: "w-4 h-4 fill-current text-gray-400" %>
            <p class="group-hover:text-indigo-600"><%= pluralize(submission.comments.size, 'comment') %></p>
          <% end %>
        </div>
        <% if author_of?(submission) %>
          <div class="pt-4 flex flex-wrap items-center">
            <%= link_to edit_submission_path(submission), class: "no-underline mr-2" do %>
              <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-indigo-600" %>
            <% end %>
            <%= button_to submission_path(submission), method: :delete, data: { confirm: "Are you sure you want to delete this submission?"},
          class: "no-underline block mt-px" do %>
              <%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-400 w-5 h-5 hover:text-indigo-600" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/submissions/_voting.html.erb
<div class="w-10 flex flex-col items-start">
  <% if user_signed_in? %>
    <%= button_to upvote_submission_path(submission),method: :put, class: "block text-center group" do %>
      <%= render_svg "icons/up-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
    <div class="flex justify-center pl-1">
      <span class="text-gray-700 text-center block" id="<%= dom_id(submission)%>_votes_count"><%= submission.total_vote_count %></span>
    </div>
    <%= button_to downvote_submission_path(submission), method: :put, class: "block text-center group"  do %>
      <%= render_svg "icons/down-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "block text-center group" do %>
      <%= render_svg "icons/up-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
    <div class="flex justify-center pl-1">
      <span class="text-gray-700 text-center block" id="<%= dom_id(submission)%>_votes_count"><%= submission.total_vote_count %></span>
    </div>
    <%= link_to new_user_session_path, class: "block text-center"  do %>
      <%= render_svg "icons/down-vote", styles: "fill-current text-gray-500 w-4 h-4 group-hover:text-indigo-600" %>
    <% end %>
  <% end %>
</div>

app/views/submissions/edit.html.erb
<% content_for :community_label, "Edit submission" %>

<% content_for :primary_content do %>
  <h1 class="text-3xl font-bold mb-6">Editing submission</h1>
  <%= render "form", submission: @submission %>
<% end %>

<% content_for :secondary_content do %>
  <%= render "guidelines" %>
<% end %>

<%= render "basic_layout" %>

app/views/submissions/index.html.erb
<%= content_for :community_label, @feed_title %>
<% content_for :primary_content do %>
  <% if @submissions.any? %>
    <div id="submissions">
      <ul class="divide-y">
        <% @submissions.each do |submission| %>
          <%= render submission %>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class="p-10 text-center">
      <div class="flex justify-center mb-3">
        <%= render_svg "icons/empty" %>
      </div>
      <p class="mb-4">Wow such empty...</p>
      <%= link_to "Create a new post", new_submission_path, class: "btn btn-indigo" %>
    </div>
  <% end %>
<% end %>

<% content_for :secondary_content do %>
  <div class="px-4 pt-4-pb-4">
    <% if user_signed_in? %>
      <h3 class="font-bold text-lg">Welcome, <%= current_user.username %></h3>
      <p class="text-gray-600 text-sm my-3"> Your personal Webbit frontpage. Come here to check in with your favorite communities.</p>
      <div class="mb-6">
        <%= link_to "New submission", new_submission_path, class: "btn btn-indigo block text-center" %>
      </div>
      <div>
        <%= link_to "New community", new_community_path, class: "btn btn-white block text-center" %>
      </div>
    <% else %>
      <%= image_tag "illustration.svg", class: "max-w-full" %>

      <h3 class="font-bold text-lg">Explore</h3>
      <p class="text-gray-600 text-sm my-3"> Find your breaking news, sports, TV fan theories, or never-ending streams of cute animals.</p>
      <%= link_to "How Webbit works", "#", class: "btn btn-indigo my-2 block block-center" %>
    <% end %>
  </div>
<% end %>
<%= render partial: "basic_layout" %>
<%# the above line could be simplified to: render "basic_layout" %>

app/views/submissions/new.html.erb
<% content_for :primary_content do %>
  <h1 class="text-3xl font-bold mb-6">New submission</h1>
  <%= render "form", submission: @submission %>
<% end %>
<% content_for :secondary_content do %>
  <%= render "guidelines" %>
<% end %>
<%= render "basic_layout" %>

app/views/submissions/show.html.erb
<% content_for :community_label, "w/#{@submission.community.name}" %>
<%= render "communities/header", community: @submission.community %>
<% content_for :primary_content do %>
  <div class="flex flex-row justify-between">
    <%# Inject the voting partial  %>
    <%= render "voting", submission: @submission %>
    <div class="flex-1">
      <p class="text-sm text-gray-600 mb-3">Posted by
        <%= link_to @submission.user.username, profile_path(@submission.user), class: "underline" %>
        <%= time_ago_in_words(@submission.created_at) + " ago" %>
      </p>
      <h1 class="font-bold text-3xl mb-6"><%= @submission.title %></h1>

      <%# The div container w. flex is additional to center it, resize_to_fit as well %>
      <div class="flex mb-6">
        <% if @submission.media.attached? %>
          <% if @submission.media.video? %>
            <%= video_tag @submission.media %>
          <% else %>
            <%= image_tag @submission.media.variant(resize_to_fit: [400, 400]), alt: @submission.title, class: "rounded" %>
          <% end %>
        <% end %>
      </div>

      <% if @submission.body? %>
        <div class="prose prose-base prose-indigo">
          <%= simple_format @submission.body %>
        </div>
      <% end %>

      <% if @submission.url? %>
        <%= link_to truncate(@submission.url, length: 100), @submission.url, class: "text-greay-700 font-mono text-indigo-500 hover:underline", target: :_blank %>
      <% end %>

      <%# Submission data %>
      <div class="flex items-center space-x-5 mt-6">
        <div class="flex items-center space-x-2">
          <%= render_svg "icons/conversation", styles: "w-5 fill-current text-gray-500" %>
          <p id="<%= dom_id(@submission)%>_comment_count"><%= pluralize(@submission.comments.size, 'comment') %></p>
        </div>
        <% if author_of?(@submission) %>
          <%= link_to edit_submission_path(@submission), class: "group" do %>
            <span class="sr-only">Edit this submission</span>
            <%= render_svg "icons/edit", styles: "w-5 fill-current text-gray-500 group-hover:text-indigo-600" %>
          <% end %>
          <%= button_to submission_path(@submission), method: :delete, class: "group" do %>
            <span class="sr-only">Delete this submission</span>
            <%= render_svg "icons/delete", styles: "w-5 fill-current text-gray-500 mt-1 group-hover:text-indigo-600" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mt-6 pt-6 border-t border-gray-300">
    <!-- updated div id to match what's in the create and destroy .turbo_stream.erb files - "new_comment_form" id -->
    <% if user_signed_in? %>
      <div id="new_comment_form">
        <%= render "comments/form", comment: Comment.new %>
      </div>
    <% else %>
      <div class="bg-gray-50 rounded p-4 mt-6 text-center">
        <%= link_to "Login to reply", new_user_session_path, class: "text-indigo-600 underline" %>
      </div>
    <% end %>
    <h3 id="comment_section" class="font-bold mt-6">Comments</h3>
    <div id="<%= dom_id(@submission) %>_comments">
      <% if @submission.comments.any? %>
        <%= render @submission.comments %>
      <% end %>
    </div>
  </div>
<% end %>
<% content_for :secondary_content do %>
  <%= render "communities/sidebar", community: @submission.community %>
<% end %>
<%= render "basic_layout" %>

app/views/submissions/unsubscribe.html.erb
<div class="max-w-lg my-16 mx-auto p-10 rounded-lg bg-white shadow-xl text-center">
  <h2 class="text-3xl font-bold mb-6">Successfully unsubscribed</h2>
  <%= link_to "Return to Webbit", root_path, class: "btn btn-indigo" %>
</div>