config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  resources :communities do
    resources :subscriptions
  end

  resources :submissions do
    resources :comments

    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end

    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", as: "comment_unsubscribe"

  devise_for :users
  root "submissions#index"

  resources :profiles, only: :show
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :community
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_community, only: [:create, :destroy]

  def create
    @subscription = @community.subscriptions.new
    @subscription.community = @community
    @subscription.user = current_user

    respond_to do |format|
      if @subscription.save
        format.turbo_stream
        format.html { redirect_to community_path(@community), notice: "You successfully subscribed." }
      else
        format.html { redirect_to community_path(@community), alert: "Your subscription could not be saved." }
      end
    end
  end

  def destroy
    @subscription = @community.subscriptions.where(user: current_user).first
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: community_path(@community), notice: "You successfully unsubscribed" }
    end
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end
end

app/views/subscriptions/_actions.html.erb
<% if user.communities.include? community %>
  <%= button_to "Unsubscribe", community_subscription_path(community, subscription), method: :delete, class: "btn btn-white w-full" %>
<% else %>
  <%= button_to "Subscribe", community_subscriptions_path(community), method: :post, class: "btn btn-indigo w-full" %>
<% end %>

app/views/subscriptions/create.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@community)}_subscribe" do %>
  <%= render "subscriptions/actions", subscription: @subscription, community: @community, user: current_user %>
<% end %>

<%= turbo_stream.replace "#{dom_id(@community)}_subscriptions_count", @community.subscriptions.size %>