config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  resources :communities do
    resources :subscriptions
  end

  resources :submissions do
    resources :comments

    member do
      put "upvote", to: "submissions#upvote"
      put "downvote", to: "submissions#downvote"
    end

    resources :comments do
      member do
        put "upvote", to: "comments#upvote"
        put "downvote", to: "comments#downvote"
      end
    end
  end

  get "submissions/unsubscribe/:unsubscribe_hash" => "submissions#unsubscribe", as: "comment_unsubscribe"

  devise_for :users
  root "submissions#index"

  resources :profiles, only: :show
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :user
  has_many :submissions
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions

  validates_associated :submissions
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /communities or /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1 or /communities/1.json
  def show
    @subscription = @community.subscriptions.where(user: current_user).first
  end

  # GET /communities/new
  def new
    @community = current_user.communities.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities or /communities.json
  def create
    @community = current_user.communities.new(community_params)
    @community.user = current_user

    respond_to do |format|
      if @community.save
        format.html { redirect_to community_url(@community), notice: "Community was successfully created." }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1 or /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to community_url(@community), notice: "Community was successfully updated." }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1 or /communities/1.json
  def destroy
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url, notice: "Community was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_community
    @community = Community.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def community_params
    params.require(:community).permit(:name, :title, :description, :sidebar, :user_id)
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<li id="<%= dom_id community %>" class="py-3">
  <p class="text-sm text-gray-600">w/<%= community.name %></p>
  <%= link_to community, class: "hover:text-indigo-600" do %>
    <h3 class="font-semibold"><%= community.title %></h3>
  <% end %>
  <div class="prose prose-indigo mb-4"><%= truncate(community.description, length: 140) %></div>
  <p class="text-xs text-gray-500">Last updated <%= community.updated_at.to_formatted_s(:nice) %></p>
  <% if author_of?(community) %>
    <div class="mt-6 flex items-center space-x-3">
      <%= link_to edit_community_path(community), class: "btn btn-white inline-flex items-center text-gray-600 text-sm" do %>
        <%= render_svg "icons/edit", styles: "w-4 h-4 fill-current text-gray-500 mr-2" %>
        Edit
      <% end %>
      <%= button_to community_path(community), method: :delete, class: "btn btn-white inline-flex items-center text-gray-600 text-sm group hover:text-red-600" do %>
        <%= render_svg "icons/delete", styles: "w-4 h-4 fill-current text-gray-500 mr-2 group group-hover:text-red-600" %>
        Delete
      <% end %>
    </div>
  <% end %>
</li>

app/views/communities/_form.html.erb
<%= form_with(model: community) do |form| %>
  <% if community.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>
      <ul>
        <% community.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-6">
    <%= form.label :name %>
    <%= form.text_field :name, class: "input" %>
  </div>
  <div class="mb-6">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input" %>
  </div>
  <div class="mb-6">
    <%= form.label :description %>
    <%= form.text_area :description, class: "input min-h-[140px]" %>
  </div>
  <div class="mb-6">
    <%= form.label :sidebar %>
    <%= form.text_area :sidebar, class: "input min-h-[140px]" %>
  </div>
  <div>
    <%= form.submit class: "btn btn-indigo" %>
  </div>
<% end %>

app/views/communities/_header.html.erb
<div class="bg-indigo-600 py-10 -mx-10">
  <div class="container mx-auto text-white">
    <h1 class="font-bold text-3xl"><%= community.title %></h1>
    <p class="text-lg">w/<%= community.name %></p>
  </div>
</div>

app/views/communities/_sidebar.html.erb
<div class="rounded p-4">
  <div class="flex items-center justify-between pb-2 border-b mb-6">
    <div class="flex items-start flex-1">
      <%= render_svg "icons/conversation", styles: "w-4 fill-current text-indigo-600 mr-2 mt-1" %>
      <div>
        <h1 class="font-mono text-sm leading-tight">w/<%= community.name %></h1>
        <h3 class="font-bold text-2xl leading-tight"><%= community.title %></h3>
      </div>
    </div>
    <% if author_of?(community) %>
      <%= link_to "Edit", edit_community_path(community), class: "underline text-indigo-600 hover:no-underline" %>
    <% end %>
  </div>
  <div class="grid grid-cols-2 gap-3">
    <div>
      <p><%= "Submission".pluralize(community.submissions.size) %></p>
      <p class="font-bold text-2xl"><%= community.submissions.size %></p>
    </div>
    <div>
      <p>Subscribers</p>
      <p class="font-bold text-2xl">
        <span id="<%= dom_id(community) %>_subscriptions_count"><%=community.subscriptions.size %></span>
      </p>
    </div>
  </div>

  <hr class="my-6" />
  <% if user_signed_in? %>
    <div id="<%= dom_id(@community)%>_subscribe">
      <%= render "subscriptions/actions", community: @community, user: current_user, subscription: @subscription %>
    </div>
  <% else %>
    <div>
      <%= link_to "Login to subscribe", new_user_session_path, class: "btn btn-indigo w-full block text-center" %>
    </div>
  <% end %>

  <hr class="mb-6" />
  <div>
    <p>Description</p>
    <div class="prose prose-indigo my-3"><%= community.description %></div>
  </div>
  <hr class="mb-6" />
  <div>
    <p>Sidebar</p>
    <div class="prose prose-indigo my-3"><%= community.sidebar %></div>
  </div>
</div>

app/views/communities/edit.html.erb
<% content_for :community_label, "Edit community" %>
<% content_for :primary_content do %>
  <h1 class="font-bold text-3xl mb-6">Edit community</h1>
  <%= render "form", community: @community %>
<% end %>
<% content_for :secondary_content do %>
  <div class="p-4">
    <%= render_svg "community", styles: "max-w-full h-auto mb-4"%>
    <h3 class="font-bold">Edit the <%= @community.name %> community on webbit</h4>
    <p class="text-sm italic">Each community requires the following:</p>
    <ul class="mt-4 list-disc pl-6 leading-loose">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>
<%= render "basic_layout" %>

app/views/communities/index.html.erb
<% content_for :community_label, "All communities" %>
<% content_for :primary_content do %>
  <% if @communities.any? %>
    <h1 class="text-3xl font-bold mb-6">Communities</h1>
    <ul class="divide-y" id="communities">
      <% @communities.each do |community| %>
        <%= render community %>
      <% end %>
    </ul>
  <% else %>
    <div class="p-10 text-center">
      <div class="flex justify-center mb-3">
        <%= render_svg "icons/empty" %>
      </div>
      <p class="mb-4">Wow such empty...</p>
      <%= link_to "Create a new community", new_community_path, class: "btn btn-indigo" %>
    </div>
  <% end %>
<% end %>
<% content_for :secondary_content do %>
  <%= link_to "New community", new_community_path, class: "btn btn-indigo" %>
<% end %>
<%= render "basic_layout" %>

app/views/communities/new.html.erb
<% content_for :community_label, "Create a community" %>
<% content_for :primary_content do %>
  <h1 class="font-bold text-3xl mb-6">Create a community</h1>
  <%= render "form", community: @community %>
<% end %>
<% content_for :secondary_content do %>
  <div class="p-4">
    <%= render_svg "community", styles: "max-w-full h-auto mb-4"%>
    <h3 class="font-bold">Create a new community on webbit</h4>
    <p class="text-sm italic">Each community requires the following:</p>
    <ul class="mt-4 list-disc pl-6 leading-loose">
      <li>Name</li>
      <li>Title</li>
      <li>Description</li>
    </ul>
  </div>
<% end %>
<%= render "basic_layout" %>

app/views/communities/show.html.erb
<% content_for :community_label, "w/#{@community.name}"%>
<%= render "header", community: @community %>
<% content_for :primary_content do %>
  <% @community.submissions.each do |submission| %>
    <%= render "submissions/submission", submission: submission %>
  <% end %>
<% end %>
<% content_for :secondary_content do %>
  <%= render "sidebar", community: @community %>
<% end %>
<%= render "basic_layout" %>